version: '2.1'

volumes:
   geoserver-data:
   db:

services:
   db:
      image: mongo
      ports:
        - "27017-27019:27017-27019"
      restart: on-failure

   geoserver:
      image: oscarfonts/geoserver
      volumes:
        - geoserver-data:/opt/geoserver/data_dir
      ports:
        - "8080:8080"
      restart: on-failure
      healthcheck:
        test: curl --fail -s http://localhost:8080/ || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3