version: '2.1'

volumes:
   geoserver-data:
   db-mongo:
   geo-db-data:

services:
   db:
      image: kartoza/postgis:11.0-2.5
      volumes:
         - geo-db-data:/var/lib/postgresql
      ports:
        - "25434:5432"
      env_file:
      - docker-env/db.env
      restart: on-failure
      healthcheck:
        test: "exit 0"
   db-mongo:
      image: mongo
      ports:
        - "27017-27019:27017-27019"
      restart: on-failure

   geoserver:
      image: oscarfonts/geoserver
      ports:
        - "8080:8080"
      volumes:
        - ./geoserver-data:/opt/geoserver/data/docs
      restart: on-failure
      depends_on:
        db:
          condition: service_healthy
      healthcheck:
        test: curl --fail -s http://localhost:8080/ || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3