[webserver]
port = ":8080"              # port to bind the web server to. defaults ":8080"

	[webserver.headers]
	Access-Control-Allow-Origin = "*"
	Cache-Control = "no-cache, no-store, must-revalidate"

[cache]                     # configure a tile cache
type = "file"               # a file cache will cache to the local file system
basepath = "/tmp/tegola"    # where to write the file cache

# register data providers
[[providers]]
name = "sample_gpkg"
type = "gpkg"
filepath = "/opt/tegola_config/polygon_cusecs_data.gpkg"
# maps are made up of layers
	[[providers.layers]]
	name = "polygon_cusecs"
	tablename = "polygon_cusecs"
	

[[maps]]
name = "test-map"                              # used in the URL to reference this map (/maps/:map_name)

	[[maps.layers]]
	name = "test"                         # name is optional. If it's not defined the name of the ProviderLayer will be used.
	                                         # It can also be used to group multiple ProviderLayers under the same namespace.
	provider_layer = "sample_gpkg.polygon_cusecs"  # must match a data provider layer
	
